name: Deploy-Blog

on:
  push:
    branches:
      - "main"
    paths:
      - "apps/blog/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
      - "turbo.json"
      - ".nvmrc"

permissions:
  contents: read

jobs:
  deploy:
    defaults:
      run:
        working-directory: apps/blog
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_BLOG_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Setup Node.js environment
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: .nvmrc

      - name: Install Vercel CLI
        run: npm install --global vercel@62.2.0

      - name: Deploy to Vercel
        run: vercel --prod --token="$VERCEL_TOKEN"
